---
- name: reomve current secret vault
  shell: "cd $(dirname {{ app_vault_file_name }}) && git rm $(basename {{ app_vault_file_name }})"
  changed_when: false

- name: remove current CSRs to enable regeneration of Keys and corresponding CSRs
  shell: "cd {{ local_cert_path }} && git rm {{ item.name }}.csr"
  with_items:
    - "{{ app_target_instances }}"
  changed_when: false

- name: Checkin changes
  include_tasks: checkpoint.yml
