---
- name: Setup change list
  set_fact:
    _ar_os_environment_remove_list: []

- name: setup to remove current CSRs to enable regeneration of Keys and corresponding CSRs
  set_fact:
    _ar_os_environment_remove_list: "{{ _ar_os_environment_remove_list }} + ['{{ local_cert_path }}/{{ item.name }}.csr']"
  with_items:
    - "{{ app_target_instances }}"

- include_role:
    name: ar_git_repo
    tasks_from: remove
  vars:
    ar_git_repo_url: "{{ ar_os_environment_git_repo }}"
    ar_git_repo_ssh_key: "{{ ar_os_environment_git_ssh_key }}"
    ar_git_repo_ssh_key_pass: "{{ ar_os_environment_git_ssh_key_pass | default('') }}"
    ar_git_repo_commit_comment: "{{ ar_os_environment_git_comment | default('') }}"
    ar_git_repo_remove_list:
      - "{{ app_vault_file_name }}"
      - "{{ _ar_os_environment_remove_list }}"
  when: ar_os_environment_git_repo | is_git_url
  failed_when: ar_os_environment_git_repo | is_not_git_url