---
- name: reomve current secret vault
  file:
    path: "{{ app_vault_file_name }}"
    state: absent

- name: remove current CSRs to enable regeneration of Keys and corresponding CSRs
  file:
    path: "{{ local_cert_path }}/{{ item.name }}.csr"
    state: absent
  with_items:
    - "{{ app_target_instances }}"

- name: Checkin changes
  include_tasks: checkpoint.yml
